#!/bin/bash
# @author Louis Krueger - 02/2016
#
#
#
#

CHECKOUT_BRANCH=""

echo "Ready to work?"
CHECKOUT_BRANCH="git checkout master"
if [[ $CHECKOUT_BRANCH == Already* ]]; then
	echo "You are not on master or have conflicting changes. Did you GL?"
	exit 1;
fi
echo "Please enter branch name:"
read branch
if [ -n "$branch" ]; then
	CHECKOUT_BRANCH="git checkout $branch"
	if [[ $CHECKOUT_BRANCH = Switch* ]]; then
		echo "Your existing branch ($branch) has been checked out"
		exit 0; 
	fi
else
	echo "invalid branch name, exiting..."
	exit 1;
fi
echo "creating branch $branch"
git checkout -b $branch
git push origin $branch
echo "new branch ($branch) has been created!"
