#!/bin/bash
# @author Louis Krueger - 01/2016
#
# Automated external testing script for Embedded XINU.
# Given the a reference implementation and a second program,
#  run the set of tests and generate report on differences.
#


echo "Ready to work? Checking out branch"
echo "Please enter branch name:"
read branch
if [ -n "$branch" ]; then
	echo "creating branch!"
else
	echo "invalid branch name, exiting..."
	exit 1;
fi
git checkout -b $branch
git push origin $branch
echo "new branch ($branch) has been created"
