#!/bin/bash
# @author Louis Krueger - 01/2016
#
# Automated external testing script for Embedded XINU.
# Given the a reference implementation and a second program,
#  run the set of tests and generate report on differences.
#
error="0"
echo "Are you sure you would like to commit and delete your branch? (ctrl-d to escape)"
read confirm
if [ -n $confirm ]&&[ $error="0" ]; then
	echo "enter commit message:" 
	read message
	if [ -n "$message" ]&&[ $error="0" ]; then
		echo "enter branch name:"
		read branch
		if [ -n "$branch" ]; then
			git add ./
			git commit -m "$message"
			git push origin $branch
			git checkout master
		else
			error="1"
		fi
	else
		error="1"
	fi
else
	error="1"
fi
if [ $error="1" ]; then
	echo "You seem unsure Sire, please go get some fresh air, exiting..."
	exit 1;
fi
echo "new branch ($branch) has been created"
