#!/bin/bash
# @author Louis Krueger - 01/2016
#
# Automated external testing script for Embedded XINU.
# Given the a reference implementation and a second program,
#  run the set of tests and generate report on differences.
#
error="0"
echo "Are you sure you would like to commit and switch to local master head?(y/n)"
read confirm
if [ $confirm = "y" ]&&[ $error="0" ]; then
	echo "enter commit message:" 
	read message
	if [ -n "$message" ]&&[ $error="0" ]; then
		echo "enter branch name:"
		read branch
		if [ -n "$branch" ]; then
			git pull
			git add ./
			git commit -m "$message"
		else
			error="1"
		fi
	else
		error="1"
	fi
else
	error="1"
fi
if [ "$error" = "1" ]; then
	echo "You seem unsure Sire, please go get some fresh air, exiting. No changes have been made"
	exit 1;
fi
git push origin $branch
echo "switching to master"
git checkout master
echo "your branch ($branch) has been commited to the repo"
echo "contact admin for master & $branch merge"
