#!/bin/bash
# @author Louis Krueger - 02/2016
#
#

REMOTE_VERIFY="git remote -v"
CLEAN_LOCAL="rm !(.git|CKO|CM|GL) -r -f"

echo "Git Latest"
echo "Please enter username:"
read user
if [ -n "$user" ]; then
	echo "enter pw:"
	read pw
else
	echo "username is nothing, exiting..."
	exit 1;
fi
if [ -n $REMOTE_VERIFY ]; then
	git remote set-url origin https://$user:$pw@github.com/louis-krueger/Opsys.git
else
 	git remote add origin https://$user:$pw@github.com/louis-krueger/OpSys.git
fi
echo "Are you sure you would like to clean local directory and clone master?(y/n)"
read user
if [ $user = "y" ]; then
	shopt -s extglob
	git checkout master
	git fetch;
	$CLEAN_LOCAL
	git reset --hard origin/master;
	git pull origin master
	echo "$USER  up-to-date"
else
	echo "TNLN, TFTC"
fi
